# Generated by Django 6.0.3 on 2026-03-03 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blanc', models.CharField(blank=True, max_length=100, verbose_name='Blanques')),
                ('negre', models.CharField(blank=True, max_length=100, verbose_name='Negres')),
                ('resultat', models.CharField(blank=True, max_length=15, verbose_name='Resultat')),
                ('data_partida', models.CharField(blank=True, max_length=20, verbose_name='Data')),
                ('esdeveniment', models.CharField(blank=True, max_length=200, verbose_name='Esdeveniment')),
                ('pgn_text', models.TextField(verbose_name='PGN Complet')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('visibilitat', models.CharField(choices=[('PUB', 'Pública (visible per tothom)'), ('CLB', 'Club (només membres)'), ('PRI', 'Privada (només jo)')], default='CLB', max_length=3)),
                ('pujada_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('jugada_num', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentaris', to='games.partida')),
            ],
        ),
    ]
