# Generated by Django 6.0.3 on 2026-03-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentari',
            old_name='data',
            new_name='data_creacio',
        ),
    ]
