# Generated by Django 6.0.3 on 2026-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_data_comentari_data_creacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='lloc',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lloc'),
        ),
        migrations.AddField(
            model_name='partida',
            name='ronda',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ronda'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='esdeveniment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Torneig'),
        ),
    ]
