# Generated by Django 6.0.3 on 2026-03-11 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_partida_lloc_partida_ronda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('adreca', models.CharField(blank=True, max_length=200)),
                ('provincia', models.CharField(blank=True, max_length=50)),
                ('federacio', models.CharField(blank=True, default='FCE', max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('web', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom complet (com a la federació)')),
                ('fcat_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Federació Catalana')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.club')),
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
